# Generated by Django 5.1.5 on 2025-03-03 15:34

import account.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.CustomUser.upload_to_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'webp', 'jfif'])], verbose_name='Аватарка пользователя'),
        ),
        migrations.AlterField(
            model_name='newsfeed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
