# Generated by Django 5.1.5 on 2025-03-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_image_alter_newsfeed_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл или фото'),
        ),
        migrations.AlterField(
            model_name='newsfeedcomments',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='newsfeedcomments',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл или фото комментария'),
        ),
    ]
