# Generated by Django 5.1.5 on 2025-06-08 11:39

import account.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_newsfeed_file_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='ignored_requests',
            field=models.ManyToManyField(blank=True, related_name='ignored_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=account.models.CustomUser.upload_to_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'webp', 'jfif'])], verbose_name='Аватарка пользователя'),
        ),
    ]
