# Generated by Django 5.1.5 on 2025-08-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_alcohol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
