# Generated by Django 5.1.5 on 2025-02-05 10:16

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoholType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('beer', 'Пиво'), ('cognak', 'Коньяк'), ('vodka', 'Водка'), ('vine', 'Вино')], verbose_name='Тип алкоголя')),
            ],
            options={
                'verbose_name': 'Тип алкоголя',
                'verbose_name_plural': 'Типы алкоголя',
            },
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('aroma', models.CharField(blank=True, null=True, verbose_name='Аромат')),
                ('taste', models.CharField(blank=True, null=True, verbose_name='Вкус')),
                ('aftertaste', models.CharField(blank=True, null=True, verbose_name='Послевкусие')),
                ('composition', models.CharField(blank=True, null=True, verbose_name='Состав')),
                ('combition_with', models.CharField(blank=True, null=True, verbose_name='С чем сочитается')),
                ('country', models.CharField(verbose_name='Страна')),
                ('style', models.CharField(verbose_name='Стиль')),
                ('type', models.CharField(choices=[('filter', 'Фильтрованное'), ('no-filter', 'Нефильтрованное')], verbose_name='Вид')),
                ('color', models.CharField(choices=[('light', 'Светлое'), ('dark', 'Темное')], verbose_name='Цвет')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.Beer.upload_to_path, verbose_name='Изображение')),
                ('alcoholtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.alcoholtype', verbose_name='Тип алкоголя')),
            ],
            options={
                'verbose_name': 'Пиво',
                'verbose_name_plural': 'Пиво',
            },
        ),
        migrations.CreateModel(
            name='Cognak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('country', models.CharField(verbose_name='Страна')),
                ('strength', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Крепкость')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Обьем')),
                ('excerpt', models.CharField(verbose_name='Выдержка')),
                ('supply_temperature', models.CharField(verbose_name='Температура подачи')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.Cognak.upload_to_path, verbose_name='Изображение')),
                ('alcoholtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.alcoholtype', verbose_name='Тип алкоголя')),
            ],
            options={
                'verbose_name': 'Коньяк',
                'verbose_name_plural': 'Коньяк',
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История покупок',
                'verbose_name_plural': 'Истории покупок',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания')),
                ('object_id', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_reviews')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Vine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('country', models.CharField(verbose_name='Страна')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Обьем')),
                ('supply_temperature', models.CharField(verbose_name='Температура подачи')),
                ('taste', models.CharField(blank=True, null=True, verbose_name='Вкус')),
                ('color', models.CharField(choices=[('pink', 'Розовое'), ('red', 'Красное'), ('white', 'Белое')], verbose_name='Цвет')),
                ('sugar_supply', models.CharField(choices=[('dry', 'Сухое'), ('semi-dry', 'Полусухое'), ('semi-sweet', 'Полусладкое'), ('sweet', 'Сладкое')], verbose_name='Содержание сахара')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.Vine.upload_to_path, verbose_name='Изображение')),
                ('alcoholtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.alcoholtype', verbose_name='Тип алкоголя')),
            ],
            options={
                'verbose_name': 'Вино',
                'verbose_name_plural': 'Вина',
            },
        ),
        migrations.CreateModel(
            name='Vodka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('country', models.CharField(verbose_name='Страна')),
                ('strength', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Крепкость')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Обьем')),
                ('serving_temperature', models.CharField(verbose_name='Температура серверовки')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.Vodka.upload_to_path, verbose_name='Изображение')),
                ('alcoholtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.alcoholtype', verbose_name='Тип алкоголя')),
            ],
            options={
                'verbose_name': 'Водка',
                'verbose_name_plural': 'Водка',
            },
        ),
    ]
